const actions = {
  GET_AUTHETICATRION: "GET_AUTHETICATRION",
  SET_AUTHETICATRION: 'SET_AUTHETICATRION',
  GET_USER_DETAILS: 'GET_USER_DETAILS',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  ADD_USERS: "ADD_USERS",
  GET_ALL_USERS: "GET_ALL_USERS",
  SET_ALL_USERS: "SET_ALL_USERS",
  REGISTER_USER: "REGISTER_USER",
  GET_VERIFY_TOCKET: "GET_VERIFY_TOCKET",
  SET_ALL_USER_ROLES: "SET_ALL_USER_ROLES",
  GET_ALL_USER_ROLES: "GET_ALL_USER_ROLES",
  UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
  SET_LOADER: "SET_LOADER",
  SET_AUTH_ROUTE_PATH: "SET_AUTH_ROUTE_PATH",
  RESET: "RESET",
  SET_SOCKET: "SET_SOCKET",
  SET_ALL_ONLINE_USERS: "SET_ALL_ONLINE_USERS",
  SET_CONVERSATION: "SET_CONVERSATION",
  SET_VIDEO_CALL:"SET_VIDEO_CALL"
};

export default actions;